### PR TITLE
Typo corrected

### PR DESCRIPTION
**Pull request by dzacharo**
This is a typo that was include in the NSRs for a long time. It is even in the latest ballot https://cabforum.org/2019/10/04/ballot-sc21-the-network-and-certificate-systems-security-requirements-section-3-log-integrity-controls/

### CODE REVIEW

**Comment by sleevi** [comment]
I think this should be balloted.

The goal of https://cabforum.org/2015/11/18/ballots-154-and-155-convert-to-rfc-3647-framework-and-github/ was specifically to resolve matters like this. Unfortunately, the Certificate Policy Review Working Group failed to adhere to that ballot.

However, that typo has been present since the [very first version](https://273.6a1.myftpupload.com/wp-content/uploads/Network_Security_Controls_V1.pdf), which has been adopted by the Forum, and was [readopted in Ballot 180](https://cabforum.org/2017/01/07/ballot-180-readopting-brs-evgl-ev-code-signing-ncssr-guidelines-amendments/) with that typo.

**Comment by dzacharo** [comment]
> 
> 
> Setting "Request Changes" until adopted via a ballot.

This is not accurate. It was changed in [ballot 210](https://cabforum.org/2017/08/31/ballot-210-misc-changes-network-certificate-system-security-requirements/).

I hope this is acceptable so we can proceed.

**Comment by sleevi** [comment]
Thanks Dimitris, that's helpful context. The PDF redline and the GitHub redline disagree on what the changes are, which creates a challenge for:

"Make other editorial changes as indicated at https://github.com/cabforum/documents/pull/64/files and in the attached PDF" (the redline omits, the PDF includes) (neither of which add "TS", but reflect different versions of text)

This is also made messy by:
> "**ADD ETSI EN 319 411-1 to first sentence of the Scope and Applicability section so that it reads "These Network and Certificate System Security Requirements (Requirements) apply to all publicly 

but then describes a change where the TS is inserted into that paragraph where it previously did not exist. Is what is binding the description of what to do ("ADD") or is it the "so that it reads"?

This definitely highlights the value in moving off GitHub, since it appears to be another case where a ballot "clobbered" more than it stated, and the redline did not actually reflect what changed. It also highlights why the "redlines aren't authoritative" crowd do more harm to ensuring consistency than help.

**Comment by sleevi** [comment]
Approving on the basis that the wording in Ballot 210 at least provides some support for this having been reviewed, despite all of its issues.

**Pull request merged**
